name: clean_architecture_todo_app
description: An todo app.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Screen
  flutter_screenutil: ^5.8.4

  #Google fonts
  google_fonts: 4.0.1

  #state management
  flutter_bloc: ^8.1.3
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it:

  #db SQLite
  floor: ^1.4.2

  # Routes
  go_router: ^10.2.0

  #Equatable
  equatable: ^2.0.5

  intl: ^0.18.1

  #animations:
  flutter_animate: ^4.2.0+1

  formz: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.4.2

  flutter_lints: ^2.0.0

  build_runner: ^2.3.3

  json_serializable: ^6.6.2

  floor_generator: ^1.4.2

flutter:

  uses-material-design: true


